/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_visor_knight_EdgeView */

#ifndef _Included_com_visor_knight_EdgeView
#define _Included_com_visor_knight_EdgeView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_visor_knight_EdgeView
 * Method:    nativeProcessing
 * Signature: ([BIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_nativeProcessing
  (JNIEnv *, jobject, jbyteArray, jint, jint, jobject);

/*
 * Class:     com_visor_knight_EdgeView
 * Method:    setThresholdManually
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_setThresholdManually
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_visor_knight_EdgeView
 * Method:    setColorSelected
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_setColorSelected
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_visor_knight_EdgeView
 * Method:    setMedianFiltering
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_setMedianFiltering
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_visor_knight_EdgeView
 * Method:    grayscaleOnly
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_grayscaleOnly
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_visor_knight_EdgeView
 * Method:    automaticThresholding
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_automaticThresholding
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_visor_knight_EdgeView
 * Method:    logarithmicTransform
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_logarithmicTransform
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_visor_knight_EdgeView
 * Method:    setSoftEdges
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_visor_knight_EdgeView_setSoftEdges
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
