/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uncc_cci_KnightVisor_EdgeView */

#ifndef _Included_edu_uncc_cci_KnightVisor_EdgeView
#define _Included_edu_uncc_cci_KnightVisor_EdgeView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uncc_cci_KnightVisor_EdgeView
 * Method:    nativeProcessing
 * Signature: ([BIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_edu_uncc_cci_KnightVisor_EdgeView_nativeProcessing
  (JNIEnv *, jobject, jbyteArray, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
